linters:
  disable-all: true
  enable:
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code.
    - ineffassign # Detects when assignments to existing variables are not used.
    - govet # Vet examines Go source code and reports suspicious constructs.
    - staticcheck # It's a set of rules from staticcheck.dev
    - unused # Checks Go code for unused constants, variables, functions and types.
    - asasalint # Check for pass []any as any in variadic func(...any).
    - asciicheck # Checks that all code identifiers does not have non-ASCII symbols in the name.
    - bidichk # Checks for dangerous unicode character sequences.	
    - decorder # heck declaration order and count of types, constants, variables and functions.
  disable:
