linters:
  disable-all: true
  enable:
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code.
    - ineffassign # Detects when assignments to existing variables are not used.
    - govet # Vet examines Go source code and reports suspicious constructs.
  disable:
